**/*.go {
    prep: go tool tern migrate -m ./migrations -c ./migrations/tern.conf
    prep: go build ./cmd/cooksense-server
    daemon +sigterm: ./cooksense-server.exe
}

migrations/*.sql {
    prep: go tool tern migrate -m ./migrations -c ./migrations/tern.conf --destination 0
    prep: go tool tern migrate -m ./migrations -c ./migrations/tern.conf
}